CREATE TABLE "Offenders" (
  "offender_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "date_of_birth" date,
  "gender" varchar,
  "physical_desc" text,
  "prior_conviction_count" int,
  "fingerprint_data" text
);

CREATE TABLE "Crime_Categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_name" varchar,
  "crime_type" varchar,
  "max_penalty" int
);

CREATE TABLE "Locations" (
  "location_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "area_name" varchar,
  "district" varchar,
  "city" varchar,
  "risk_level" int
);

CREATE TABLE "Incidents" (
  "incident_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "offender_id" int,
  "category_id" int,
  "location_id" int,
  "occurrence_timestamp" datetime,
  "description" text,
  "status" varchar
);

CREATE TABLE "Officers" (
  "officer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "badge_number" int UNIQUE,
  "rank" varchar,
  "station_branch" varchar
);

CREATE TABLE "Assignments" (
  "assignment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "incident_id" int,
  "officer_id" int,
  "assignment_date" date
);

ALTER TABLE "Incidents" ADD FOREIGN KEY ("offender_id") REFERENCES "Offenders" ("offender_id");

ALTER TABLE "Incidents" ADD FOREIGN KEY ("category_id") REFERENCES "Crime_Categories" ("category_id");

ALTER TABLE "Incidents" ADD FOREIGN KEY ("location_id") REFERENCES "Locations" ("location_id");

ALTER TABLE "Assignments" ADD FOREIGN KEY ("incident_id") REFERENCES "Incidents" ("incident_id");

ALTER TABLE "Assignments" ADD FOREIGN KEY ("officer_id") REFERENCES "Officers" ("officer_id");
