// frontend/app/reports/page.tsx
"use client";

import { FileText, Download, Printer, Share2, Clipboard, FileCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { getCrimes, Crime } from "../../lib/api";

const TEMPLATES = [
  { id: "T1", name: "Monthly Crime Index", type: "Statistical" },
  { id: "T2", name: "Incident Investigation Summary", type: "Operational" },
  { id: "T3", name: "Personnel Performance Review", type: "Administrative" },
  { id: "T4", name: "Regional Hotspot Analysis", type: "Geospatial" },
];

export default function ReportingEngine() {
  const [crimes, setCrimes] = useState<Crime[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedTemplate, setSelectedTemplate] = useState(TEMPLATES[0]);

  useEffect(() => {
    getCrimes()
      .then(setCrimes)
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const crimeCount = crimes.length;
  const recentCrime = crimes[0] || null;

  return (
    <>
      <div className="page-header">
        <div>
          <h1 className="page-title">Reporting Engine</h1>
          <p className="page-subtitle">Generate court-admissible documents and executive summaries.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-[300px,1fr] gap-8 items-start">
        {/* Template Selector */}
        <div className="flex flex-col gap-4">
          <div className="label">Available Templates</div>
          <div className="flex flex-col gap-2">
            {TEMPLATES.map((t) => (
              <button 
                key={t.id} 
                onClick={() => setSelectedTemplate(t)}
                className={`text-left p-3 border transition-colors flex flex-col ${selectedTemplate.id === t.id ? 'bg-accent border-accent text-white' : 'bg-surface border-border text-primary hover:border-accent'}`}
              >
                <span className="text-[12px] font-bold">{t.name}</span>
                <span className={`text-[10px] uppercase font-mono mt-1 ${selectedTemplate.id === t.id ? 'text-white/70' : 'text-secondary'}`}>{t.type}</span>
              </button>
            ))}
          </div>

          <div className="mt-6 border border-border p-4 bg-surface/30">
            <div className="label mb-3 text-secondary text-[10px]">Technical Note // Formatting</div>
            <div className="text-[11px] text-dim font-mono leading-relaxed">
              Reports are generated via a specialized LaTeX / Headless-Chrome pipeline on the Go backend for precise alignment.
            </div>
          </div>
        </div>

        {/* Report Preview */}
        <div className="flex flex-col gap-6 w-full">
          <div className="border border-border bg-white text-black min-h-[600px] flex flex-col">
            {/* Document Header */}
            <div className="p-8 border-b border-gray-200">
              <div className="flex justify-between items-start">
                <div>
                  <div className="text-[10px] font-bold tracking-widest uppercase mb-1">State of Tamil Nadu</div>
                  <div className="text-xl font-bold uppercase tracking-tight">Chennai Metropolitan Police</div>
                  <div className="text-[11px] text-gray-500 font-serif italic mt-1 font-bold">Standard Form No. CRPA-09 // {selectedTemplate.id}</div>
                </div>
                <div className="w-12 h-12 border-2 border-black flex items-center justify-center font-bold text-xs">OFFICIAL</div>
              </div>
            </div>

            {/* Document Body */}
            <div className="p-8 flex-1 font-serif text-[13px] leading-relaxed">
              <div className="mb-6 font-bold text-lg text-center underline decoration-2 underline-offset-4">{selectedTemplate.name.toUpperCase()}</div>
              
              <div className="grid grid-cols-[120px,1fr] gap-y-2 mb-8">
                <div className="font-bold">Prepared At:</div> <div>Chennai Intelligence HQ</div>
                <div className="font-bold">Date:</div> <div>{new Date().toLocaleDateString('en-GB')}</div>
                <div className="font-bold">Classification:</div> <div className="text-red-600 font-bold">RESTRICTED // INTERNAL USE ONLY</div>
              </div>

              <div className="space-y-4">
                <p>This document constitutes an official report generated by the Chennai Regional Pattern Analysis (CRPA) system. The data contained herein is aggregated from the Centralized Incident Database (CID) via secure pgxpool connections.</p>
                
                <div className="p-4 bg-gray-50 border border-gray-200 mt-6 italic">
                  "The analysis indicates {crimeCount} total records in the current database. The latest recorded incident {recentCrime ? `is classified as ${recentCrime.crime_type} occurring at ${recentCrime.area_name}` : "is pending synchronization"}."
                </div>

                <div className="mt-12 pt-8 border-t-2 border-dotted border-gray-300 flex justify-between">
                  <div className="text-center w-40">
                    <div className="border-b border-black mb-1"></div>
                    <div className="text-[10px] font-bold uppercase">Authorized Signatory</div>
                  </div>
                  <div className="text-center w-40">
                    <div className="border-b border-black mb-1"></div>
                    <div className="text-[10px] font-bold uppercase">System Verification Hash</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Toolbar */}
            <div className="bg-bg-base border-t border-border p-3 flex justify-between items-center text-primary">
              <div className="flex gap-2">
                <button className="p-2 border border-border hover:bg-surface"><Download size={14} /></button>
                <button className="p-2 border border-border hover:bg-surface"><Printer size={14} /></button>
                <button className="p-2 border border-border hover:bg-surface"><Share2 size={14} /></button>
              </div>
              <div className="text-[10px] font-mono text-dim">GENERATING DOCUMENT... [OK]</div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
